import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    navHome: 'Home',
    navDashboard: 'Farmer Dashboard',
    navDetect: 'AI Disease Detection',
    navWeather: 'Weather Risk',
    navRiskMap: 'Risk Map',
    navExpert: 'Expert Validation',
    navAdmin: 'Admin Command',
    heroTag: 'PRECISION AGRI-VISION • SMART CROP PROTECTION',
    heroTitle: 'AI-Powered Early Crop Protection & Risk Forecasting',
    heroDesc: 'Empowering Indian farmers with instant AI disease diagnosis, smart pest traps, IoT microclimate modeling, 4-tier IPDM strategies, safe pesticide calculators, and verified agronomist advisories.',
    btnCheckCrop: 'Check Crop Health',
    btnDashboard: 'View Dashboard',
    disclaimerTitle: 'AI Transparency & Model Assurance',
    disclaimerDesc: 'All predictions are computed using neural vision models (YOLOv8 architecture) calibrated with microclimate parameters. High-risk cases can be escalated directly to certified agronomists and KVK diagnostic labs.',
    statScans: 'Crops Scanned',
    statAccuracy: 'Model Accuracy',
    statDistricts: 'Districts Covered',
    statResponse: 'Avg Response Time',
    mockBadge: 'Demo Mode (FastAPI Ready)',
  },
  hi: {
    navHome: 'मुख्य पृष्ठ',
    navDashboard: 'किसान डैशबोर्ड',
    navDetect: 'एआई रोग पहचान',
    navWeather: 'मौसम जोखिम',
    navRiskMap: 'जोखिम मानचित्र',
    navExpert: 'विशेषज्ञ सत्यापन',
    navAdmin: 'एडमिन कमांड',
    heroTag: 'सटीक कृषि-दृष्टि • स्मार्ट फसल सुरक्षा',
    heroTitle: 'एआई संचालित फसल सुरक्षा और मौसम जोखिम पूर्वानुमान',
    heroDesc: 'भारतीय किसानों को त्वरित एआई फसल रोग निदान, कीट ट्रैप और सेंसर डेटा, 4-स्तरीय आईपीडीएम सलाह और सुरक्षित कीटनाशक खुराक से सशक्त बनाना।',
    btnCheckCrop: 'फसल स्वास्थ्य जांचें',
    btnDashboard: 'डैशबोर्ड देखें',
    disclaimerTitle: 'एआई पारदर्शिता और मॉडल आश्वासन',
    disclaimerDesc: 'सभी पूर्वानुमान YOLOv8 विज़न मॉडल द्वारा तैयार किए जाते हैं। संदिग्ध मामलों को सीधे कृषि विज्ञान केंद्र (KVK) प्रयोगशाला में भेजा जा सकता है।',
    statScans: 'स्कैन की गई फसलें',
    statAccuracy: 'मॉडल सटीकता',
    statDistricts: 'कवर किए गए जिले',
    statResponse: 'औसत प्रतिक्रिया समय',
    mockBadge: 'डेमो मोड (FastAPI तैयार)',
  },
  mr: {
    navHome: 'मुख्यपृष्ठ',
    navDashboard: 'शेतकरी डॅशबोर्ड',
    navDetect: 'एआय रोग निदान',
    navWeather: 'हवामान धोके',
    navRiskMap: 'धोका नकाशा',
    navExpert: 'तज्ज्ञ पडताळणी',
    navAdmin: 'अ‍ॅडमिन कमांड',
    heroTag: 'अचूक कृषी-दृष्टी • स्मार्ट पीक संरक्षण',
    heroTitle: 'एआय द्वारे पीक रोग शोध आणि हवामान अंदाज',
    heroDesc: 'भारतीय शेतकऱ्यांना त्वरित एआय पीक रोग निदान, कीटक ट्रॅप डेटा, 4-स्तरीय IPDM सल्ला आणि सुरक्षित कीटकनाशक मार्गदर्शन देणे.',
    btnCheckCrop: 'पिकांचे आरोग्य तपासा',
    btnDashboard: 'डॅशबोर्ड पहा',
    disclaimerTitle: 'एआय पारदर्शकता',
    disclaimerDesc: 'सर्व निदान YOLOv8 मॉडेलद्वारे केले जातात आणि केव्हीके तज्ज्ञांकडून पडताळले जाऊ शकतात.',
    statScans: 'स्कॅन पिके',
    statAccuracy: 'मॉडेल अचूकता',
    statDistricts: 'जिल्हे',
    statResponse: 'प्रतिसाद वेळ',
    mockBadge: 'डेमो मोड (FastAPI तयार)',
  },
  pa: {
    navHome: 'ਮੁੱਖ ਪੰਨਾ',
    navDashboard: 'ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ',
    navDetect: 'ਏਆਈ ਬੀਮਾਰੀ ਜਾਂਚ',
    navWeather: 'ਮੌਸਮ ਖਤਰਾ',
    navRiskMap: 'ਖਤਰਾ ਨਕਸ਼ਾ',
    navExpert: 'ਮਾਹਰ ਤਸਦੀਕ',
    navAdmin: 'ਐਡਮਿਨ ਕਮਾਂਡ',
    heroTag: 'ਸਹੀ ਖੇਤੀਬਾੜੀ ਦ੍ਰਿਸ਼ਟੀ • ਸਮਾਰਟ ਫਸਲ ਸੁਰੱਖਿਆ',
    heroTitle: 'ਏਆਈ ਨਾਲ ਫਸਲ ਦੀ ਸੁਰੱਖਿਆ ਅਤੇ ਮੌਸਮ ਦਾ ਅਨੁਮਾਨ',
    heroDesc: 'ਕਿਸਾਨਾਂ ਲਈ ਫਸਲੀ ਬੀਮਾਰੀਆਂ ਦੀ ਤੁਰੰਤ ਪਛਾਣ, ਕੀੜੇ-ਮਕੌੜੇ ਟਰੈਪ ਡੇਟਾ, ਅਤੇ ਖੇਤੀਬਾੜੀ ਮਾਹਰਾਂ ਦੀ ਸਲਾਹ।',
    btnCheckCrop: 'ਫਸਲ ਦੀ ਜਾਂਚ ਕਰੋ',
    btnDashboard: 'ਡੈਸ਼ਬੋਰਡ ਵੇਖੋ',
    disclaimerTitle: 'ਏਆਈ ਪਾਰਦਰਸ਼ਤਾ',
    disclaimerDesc: 'ਸਾਰੇ ਅਨੁਮਾਨ YOLOv8 ਮਾਡਲ ਦੁਆਰਾ ਕੀਤੇ ਜਾਂਦੇ ਹਨ ਅਤੇ ਕੇ.ਵੀ.ਕੇ. ਲੈਬ ਨੂੰ ਭੇਜੇ ਜਾ ਸਕਦੇ ਹਨ।',
    statScans: 'ਜਾਂਚ ਕੀਤੀਆਂ ਫਸਲਾਂ',
    statAccuracy: 'ਮਾਡਲ ਸ਼ੁੱਧਤਾ',
    statDistricts: 'ਜ਼ਿਲ੍ਹੇ',
    statResponse: 'ਔਸਤ ਸਮਾਂ',
    mockBadge: 'ਡੈਮੋ ਮੋਡ (FastAPI ਤਿਆਰ)',
  },
  te: {
    navHome: 'హోమ్',
    navDashboard: 'రైతు డాష్‌బోర్డ్',
    navDetect: 'AI వ్యాధి గుర్తింపు',
    navWeather: 'వాతావరణ ప్రమాదం',
    navRiskMap: 'రిస్క్ మ్యాప్',
    navExpert: 'నిపుణుల ధృవీకరణ',
    navAdmin: 'అడ్మిన్ కమాండ్',
    heroTag: 'ఖచ్చితమైన వ్యవసాయ రక్షణ • స్మార్ట్ పంట సంరక్షణ',
    heroTitle: 'AI ఆధారిత పంట సంరక్షణ & వాతావరణ హెచ్చరికలు',
    heroDesc: 'భారతీయ రైతులకు తక్షణ AI పంట వ్యాధి నిర్ధారణ, తెగుళ్ల ట్రాప్ డేటా, IPDM సలహాలు మరియు సురక్షిత పురుగుమందుల మోతాదు.',
    btnCheckCrop: 'పంట ఆరోగ్యాన్ని తనిఖీ చేయండి',
    btnDashboard: 'డాష్‌బోర్డ్ చూడండి',
    disclaimerTitle: 'AI పారదర్శకత',
    disclaimerDesc: 'అన్ని అంచనాలు YOLOv8 మోడల్స్ ద్వారా లెక్కించబడతాయి.',
    statScans: 'స్కాన్ చేసిన పంటలు',
    statAccuracy: 'మోడల్ ఖచ్చితత్వం',
    statDistricts: 'జిల్లాల సంఖ్య',
    statResponse: 'సరాసరి సమయం',
    mockBadge: 'డెమో మోడ్ (FastAPI సద్ధం)',
  },
  ta: {
    navHome: 'முகப்பு',
    navDashboard: 'விவசாயி டாஷ்போர்டு',
    navDetect: 'AI நோய் கண்டறிதல்',
    navWeather: 'வானிலை அபாயம்',
    navRiskMap: 'அபாய வரைபடம்',
    navExpert: 'நிபுணர் சரிபார்ப்பு',
    navAdmin: 'நிர்வாகக் கட்டளை',
    heroTag: 'துல்லிய விவசாய பார்வை • ஸ்மார்ட் பயிர் பாதுகாப்பு',
    heroTitle: 'செயற்கை நுண்ணறிவு பயிர் பாதுகாப்பு & வானிலை கணிப்பு',
    heroDesc: 'விவசாயிகளுக்கு உடனடி AI நோய் கண்டறிதல், பூச்சி பொறி தரவு மற்றும் வேளாண் நிபுணர் ஆலோசனைகள்.',
    btnCheckCrop: 'பயிர் ஆரோக்கியத்தை சரிபார்க்கவும்',
    btnDashboard: 'டாஷ்போர்டைப் பார்க்கவும்',
    disclaimerTitle: 'AI வெளிப்படைத்தன்மை',
    disclaimerDesc: 'அனைத்து கணிப்புகளும் YOLOv8 மாதிரிகளால் கணக்கிடப்படுகின்றன.',
    statScans: 'கண்டறியப்பட்ட பயிர்கள்',
    statAccuracy: 'துல்லியம்',
    statDistricts: 'மாவட்டங்கள்',
    statResponse: 'சராசரி நேரம்',
    mockBadge: 'டெமோ பயன்முறை',
  },
  bn: {
    navHome: 'হোম',
    navDashboard: 'কৃষক ড্যাশবোর্ড',
    navDetect: 'এআই রোগ সনাক্তকরণ',
    navWeather: 'আবহাওয়া ঝুঁকি',
    navRiskMap: 'ঝুঁকি মানচিত্র',
    navExpert: 'বিশেষজ্ঞ যাচাইকরণ',
    navAdmin: 'অ্যাডমিন কমান্ড',
    heroTag: 'নির্ভুল কৃষি-দৃষ্টি • স্মার্ট ফসল সুরক্ষা',
    heroTitle: 'এআই চালিত ফসল সুরক্ষা এবং রোগ পূর্বাভাস',
    heroDesc: 'ভারতীয় কৃষকদের জন্য দ্রুত এআই রোগ নির্ণয়, পোকা ফাঁদ পর্যবেক্ষণ, ৪-স্তরের আইপিডিএম কৌশল এবং নিরাপদ কীটনাশক নির্দেশিকা।',
    btnCheckCrop: 'ফসলের স্বাস্থ্য পরীক্ষা করুন',
    btnDashboard: 'ড্যাশবোর্ড দেখুন',
    disclaimerTitle: 'এআই স্বচ্ছতা ও নিশ্চয়তা',
    disclaimerDesc: 'সকল পূর্বাভাস YOLOv8 ভিশন মডেল দ্বারা গণনা করা হয় এবং সরাসরি কেভিকে ল্যাবে রেফার করা যায়।',
    statScans: 'স্ক্যান করা ফসল',
    statAccuracy: 'মডেল নির্ভুলতা',
    statDistricts: 'আওতাভুক্ত জেলা',
    statResponse: 'গড় প্রতিক্রিয়া সময়',
    mockBadge: 'ডেমো মোড (FastAPI প্রস্তুত)',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
